## loading libraries 
import pandas as pd 
from pathlib import Path 
import os

In [23]:
import pandas as pd
import os

In [24]:
def loadHotelBooking():
    global HotelBookingDF
    HotelBookingDF = pd.read_excel("hotel_room_occupancy.xlsx",dtype=object)

In [25]:
#checking for available room
# this shows the available room in the hotel that we can use to book the customers 
def checkAvRoom():
    AvailableRoom = HotelBookingDF[HotelBookingDF['Name'] == 'Not Occupied']
    print(AvailableRoom)

In [26]:
# After using def checkAvRoom() to see which room are available we can use the below code to add the new -
# customer to the available room
# Allocating customer to room - we have not been told to add a customer to the available room 
# Therefore I am going to update and the change the Available default setting to the Customer Booking Information
def getNewCustomerBooking():
    Room_No = int(input("Enter the Room_No: "))
    if not HotelBookingDF['Room_No'].isin([Room_No]).any():
        print(f"The entered Room_No is non-existent.")
        return
    
    done = False
    while not done:
        try:
            CustomerName = input("Enter the name of the customer: ")
            Date = input("Enter the start booking date: ")
            Day =int(input("Enter the total days of stay: "))
            dateformat = pd.to_datetime(Date,format="%Y-%m-%d")
            done = True 
            
            HotelBookingDF.loc[HotelBookingDF['Room_No'] == Room_No, 'Name'] = CustomerName
            HotelBookingDF.loc[HotelBookingDF['Room_No'] == Room_No, 'Date_Occupancy'] = Date # Date Format = yyyy-mm-dd
            HotelBookingDF.loc[HotelBookingDF['Room_No'] == Room_No, 'Days_Occupancy'] = Day
            print("Room", Room_No, " has been added")
        except(ValueError):
            print("ValueError: Please Enter an INTEGER")

In [27]:
#checking for occupied room
# this shows the occupied room by the existing customer 
def checkOccRoom():
    OccupiedRoom = HotelBookingDF[HotelBookingDF['Name'] != 'Not Occupied']
    print(OccupiedRoom)

In [28]:
# we will be using Room_No to identify the updates needed for the people in that room 
# with the code below you can update the no.of day occupancy with the room number 
def UpdateDays():
    Room_No = int(input("Enter the Room_No: "))
    if not HotelBookingDF['Room_No'].isin([Room_No]).any(): # to check if the room number given is in the xlsx file 
        print(f"The entered Room_No is non-existent.")
        return
    
    UpdateChanges = "Days_Occupancy"
    if UpdateChanges == "Days_Occupancy":
        try:
            UpdatedDays=int(input("Updated Day Occupancy:"))
            HotelBookingDF.loc[HotelBookingDF["Room_No"] == Room_No, "Days_Occupancy"] = UpdatedDays
            print("The updated number of Day_Occupancy is:",UpdatedDays)
        except(ValueError): # to check if in case the person enters "Twenty" instead of "20"
            print("Please Enter an INTEGER.")
    else:
        pass

In [29]:
# to delete the customer recorde and change it to the default value 
# I will be using the customer name to delete the data related
# Name = Not Occupied
# Date_ Occupancy = 01-01-22
# Days_Occupancy = 0 
def DefaultValue():
    DefaultName = "Not Occupied"
    DefaultDate = "2022-01-01"
    DefaultDays = 0
    dateformat = pd.to_datetime(DefaultDate,format="%Y-%m-%d") # to keep the format of the date 
    Room_No = int(input("Enter the Room_Number: "))
    if Room_No in list(HotelBookingDF['Room_No']):
        HotelBookingDF.loc[HotelBookingDF['Room_No'] == Room_No, 'Name'] = DefaultName
        HotelBookingDF.loc[HotelBookingDF['Room_No'] == Room_No, 'Date_Occupancy'] = DefaultDate
        HotelBookingDF.loc[HotelBookingDF['Room_No'] == Room_No, 'Days_Occupancy'] = DefaultDays
        print("Customer info has been deleted successfully.")
    else:
        print(f"The entered Room_No is non-existent.")

In [30]:
def SaveUpdatedFile():
    filepath = Path('hotel_room_occupancy.xlsx')
    HotelBookingDF.to_excel(filepath)
    print("File has been saved at 'hotel_room_occupancy.xlsx'.")

In [31]:
# display menu and get choice
def menu():
    print("\nMENU")
    print("A. Check for available rooms")
    print("B. Allot a room")
    print("C. Update occupancy for existing customer")
    print("D. Display occupied room")
    print("E. Checkout Customer")
    print("F. Save Updated file")
    print("Q. Quit application")
    choice = input("SELECT CHOICE: ")
    print("\n")
    return choice

In [32]:
loadHotelBooking()

# despatch user's choice
selected = "X"
while selected != 'Q' and selected !='q':
    if selected == 'A' or selected =='a':
        checkAvRoom()
    elif selected == 'B' or selected =='b':
        getNewCustomerBooking()
    elif selected == 'C' or selected =='c':
        UpdateDays()
    elif selected == 'D' or selected =='d':
        checkOccRoom()
    elif selected == 'E' or selected =='e':
        DefaultValue()
    elif selected == 'F' or selected =='f':
        SaveUpdatedFile()
    else: pass

    selected = menu()

MENU
A. Check for available rooms
B. Allot a room
C. Update occupancy for existing customer
D. Display occupied room
E. Checkout Customer
F. Save Updated file
Q. Quit application
SELECT CHOICE: a


   Unnamed: 0 Room_No          Name Date_Occupancy Days_Occupancy  \
2           2     203  Not Occupied     2022-01-01              0
6           6     207  Not Occupied     2022-01-01              0
7           7     208  Not Occupied     2022-01-01              0
9           9     210  Not Occupied     2022-01-01              0
11         11     302  Not Occupied     2022-01-01              0
12         12     303  Not Occupied     2022-01-01              0
18         18     309  Not Occupied     2022-01-01              0
19         19     310  Not Occupied     2022-01-01              0
23         23     404  Not Occupied     2022-01-01              0
24         24     405  Not Occupied     2022-01-01              0
29         29     410  Not Occupied     2022-01-01              0

     Type_of_Room Rate_per_Day
2          Single          300
6          Double          500
7          Double          500
9   Double Deluxe          600
11         Single          300
12         Single          300
18  Double Deluxe          600
19  Double Deluxe          600
23         Single          300
24         Double          500
29  Double Deluxe          600

MENU
A. Check for available rooms
B. Allot a room
C. Update occupancy for existing customer
D. Display occupied room
E. Checkout Customer
F. Save Updated file
Q. Quit application
SELECT CHOICE: b


Enter the Room_No: 203
Enter the name of the customer: Swetha
Enter the start booking date: 2022-01-01
Enter the total days of stay: 2
Room 203  has been added

MENU
A. Check for available rooms
B. Allot a room
C. Update occupancy for existing customer
D. Display occupied room
E. Checkout Customer
F. Save Updated file
Q. Quit application
SELECT CHOICE: d


   Unnamed: 0 Room_No        Name Date_Occupancy Days_Occupancy  \
0           0     201   Alice Lim     2022-08-12             30
1           1     202    Beth Low     2022-08-19             20
2           2     203     Swetha      2022-01-01              2
3           3     204     Don Poh     2022-08-22             10
4           4     205  Evans King     2022-08-17             20
5           5     206  French Koh     2022-08-19             30
8           8     209    Indie Li     2022-08-17             15
10         10     301   King Hock     2022-08-21             20
13         13     304     Nin Non     2022-08-22             18
14         14     305    Olly Loh     2022-08-19             16
15         15     306    Peon Sim     2022-08-20             20
16         16     307      Qu Lin     2022-08-15             13
17         17     308     Ron Tan     2022-08-13             12
20         20     401      Ur Ler     2022-08-20             20
21         21     402   Vince Cer     2022-08-15             15
22         22     403    Win Ning     2022-08-13             30
25         25     406     Zoe Lim     2022-08-22             23
26         26     407   Apple Man     2022-08-13             14
27         27     408      Bin Ni     2022-08-20             16
28         28     409    Cathy Ho     2022-08-15             22

     Type_of_Room Rate_per_Day
0          Single          300
1          Single          300
2          Single          300
3          Single          300
4          Double          500
5          Double          500
8   Double Deluxe          600
10         Single          300
13         Single          300
14         Double          500
15         Double          500
16         Double          500
17         Double          500
20         Single          300
21         Single          300
22         Single          300
25         Double          500
26         Double          500
27         Double          500
28  Double Deluxe          600

MENU
A. Check for available rooms
B. Allot a room
C. Update occupancy for existing customer
D. Display occupied room
E. Checkout Customer
F. Save Updated file
Q. Quit application
SELECT CHOICE: q

In [33]:
HotelBookingDF # to check the table

,Unnamed: 0,Room_No,Name,Date_Occupancy,Days_Occupancy,Type_of_Room,Rate_per_Day
0,0,201,Alice Lim,2022-08-12,30,Single,300
1,1,202,Beth Low,2022-08-19,20,Single,300
2,2,203,Swetha,2022-01-01,2,Single,300
3,3,204,Don Poh,2022-08-22,10,Single,300
4,4,205,Evans King,2022-08-17,20,Double,500
5,5,206,French Koh,2022-08-19,30,Double,500
6,6,207,Not Occupied,2022-01-01,0,Double,500
7,7,208,Not Occupied,2022-01-01,0,Double,500
8,8,209,Indie Li,2022-08-17,15,Double Deluxe,600
9,9,210,Not Occupied,2022-01-01,0,Double Deluxe,600
10,10,301,King Hock,2022-08-21,20,Single,300
11,11,302,Not Occupied,2022-01-01,0,Single,300
12,12,303,Not Occupied,2022-01-01,0,Single,300
13,13,304,Nin Non,2022-08-22,18,Single,300
14,14,305,Olly Loh,2022-08-19,16,Double,500
15,15,306,Peon Sim,2022-08-20,20,Double,500
16,16,307,Qu Lin,2022-08-15,13,Double,500
17,17,308,Ron Tan,2022-08-13,12,Double,500
18,18,309,Not Occupied,2022-01-01,0,Double Deluxe,600
19,19,310,Not Occupied,2022-01-01,0,Double Deluxe,600
20,20,401,Ur Ler,2022-08-20,20,Single,300
21,21,402,Vince Cer,2022-08-15,15,Single,300
22,22,403,Win Ning,2022-08-13,30,Single,300
23,23,404,Not Occupied,2022-01-01,0,Single,300
24,24,405,Not Occupied,2022-01-01,0,Double,500
25,25,406,Zoe Lim,2022-08-22,23,Double,500
26,26,407,Apple Man,2022-08-13,14,Double,500
27,27,408,Bin Ni,2022-08-20,16,Double,500
28,28,409,Cathy Ho,2022-08-15,22,Double Deluxe,600
29,29,410,Not Occupied,2022-01-01,0,Double Deluxe,600